apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    #opendatahub.io/accelerator-name: nvidia
    opendatahub.io/apiProtocol: REST
    #opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: Caikit TGIS ServingRuntime for KServe
    opendatahub.io/template-name: caikit-tgis-runtime
    openshift.io/display-name: test
  name: test
spec:
  containers:
    - args:
        - '--model-name=/mnt/models/artifacts/'
      command:
        - text-generation-launcher
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      image: 'quay.io/modh/text-generation-inference@sha256:b87d83c65c9c5897d8a6881a160f5c65b9d7ba1d8a27bdc1ee229e60af654a9c'
      name: kserve-container
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
    - env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        - name: RUNTIME_GRPC_ENABLED
          value: 'false'
        - name: RUNTIME_HTTP_ENABLED
          value: 'true'
        - name: RUNTIME_GRPC_SERVER_THREAD_POOL_SIZE
          value: '64'
      image: 'quay.io/modh/caikit-tgis-serving@sha256:444bca43c99bfc4b961c926f5f10c556488613912f5e333011e98b3407d76d00'
      livenessProbe:
        exec:
          command:
            - python
            - '-m'
            - caikit_health_probe
            - liveness
      name: transformer-container
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - python
            - '-m'
            - caikit_health_probe
            - readiness
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: caikit
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
