apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
  - ./telemetry.yaml   

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
  - name: gateway
    releaseName: ingress-gateway
    namespace: istio-system
    valuesFile: ingress-gateway-values.yaml