apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: tempo-oltp-http
spec:
  hosts:
  - tempo-tempo-distributor.openshift-tempo-instance.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - number: 9411
    name: http
    protocol: TCP
  resolution: DNS