apiVersion: v1
kind: Secret
metadata:
  name: dsc-tenant-s3
  namespace: redhat-ods-applications  
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'false'
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
    opendatahub.io/connection-type: s3
    openshift.io/display-name: dsc-shared
stringData:
  # access_key_id: dsc
  # access_key_secret: dscdscdsc
  # bucketnames: models
  # endpoint: http://minio.redhat-ods-applications.svc.cluster.local
  AWS_ACCESS_KEY_ID: dsc=
  AWS_DEFAULT_REGION: ''
  AWS_S3_BUCKET: models
  AWS_S3_ENDPOINT: http://minio.redhat-ods-applications.svc.cluster.local
  AWS_SECRET_ACCESS_KEY: dscdscdsc
  aws_connection_dsc: '{"access_key_id":"dsc","bucket":"models","default_bucket":"models","endpoint_url":"http://minio.redhat-ods-applications.svc.cluster.local","region":"","secret_access_key":"dscdscdsc","type":"s3"}'
