apiVersion: v1
kind: Secret
metadata:
  name: dsc-tenant-s3
stringData:
  access_key_id: dsc
  access_key_secret: dscdscdsc
  bucketnames: models
  endpoint: http://minio.redhat-ods-applications.svc.cluster.local
