apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redhat-ods-applications

resources:
  - ./hf_tgi-serving-template.yaml
  - ./ollama-serving-template.yaml
  - ./vllm-serving-template.yaml
  - ./accelerator-profile.yaml
  - ./dsc-tenant-route.yaml
  - ./dsc-tenant-secret.yaml
  - ./rbac.yaml
  - ./network-policy.yaml  


helmCharts:
  - name: tenant
    repo: https://operator.min.io
    releaseName: dsc
    namespace: redhat-ods-applications
    valuesFile: values.yaml   