apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
spec:
  applicationsNamespace: redhat-ods-applications
  serviceMesh:
    managementState: Unmanaged
  trustedCABundle:
    managementState: Managed 
    customCABundle: ""
  