apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ./cluster-policy.yaml

configMapGenerator:
- name: nvidia-dcgm-exporter-dashboard
  namespace: openshift-config-managed
  files:
    - dcm-exporter-dashboard.json
  options:
    disableNameSuffixHash: true
    labels:
      console.openshift.io/dashboard: "true"
      console.openshift.io/odc-dashboard: "true"      
