apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo-stack

resources:
  - ./namespace.yaml
  - ./tempo-stack.yaml
  - ./link.yaml  


helmCharts:
  - name: gateway
    releaseName: ingress-gateway
    namespace: istio-system
    valuesFile: ingress-gateway-values.yaml

  - name: tenant
    repo: https://operator.min.io
    releaseName: tempo
    namespace: tempo-stack
    valuesFile: values.yaml      