apiVersion: v1
kind: Secret
metadata:
  name: tempo-tenant
stringData:
  endpoint:  http://tempo-hl.tempo-stack.svc:9000
  bucket: tempo
  access_key_id: tempo
  access_key_secret: tempotempo
type: Opaque