# apiVersion: tempo.grafana.com/v1alpha1
# kind: TempoMonolithic
# metadata:
#   name: tempo
#   namespace: tempo-stack
# spec:
#   storage:
#     traces:
#       backend: memory
#       size: 2Gi
#   jaegerui:                              # JaegerUI defines the Jaeger UI configuration.
#     enabled: true  
#     route:                               # Route defines the OpenShift route configuration for the Jaeger UI.
#       enabled: true                     # Enabled defines if a Route object should be created for Jaeger UI.
#       annotations: {}                    # Annotations defines the annotations of the Route object.
#       termination: "edge"
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
  namespace: tempo-stack
spec:
  storageSize: 35Gi
  storage: 
    secret:
      name: tempo-tenant
      type: s3
  observability:
    metrics:
      createServiceMonitors: true
      createPrometheusRules: true
  template:
    queryFrontend:
      jaegerQuery: 
        enabled: true
        ingress:
          route:
            termination: edge
          type: route                