apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: sample
  namespace: tempo-stack
spec:
  storage:
    traces:
      backend: memory
      size: 2Gi
  jaegerui:                              # JaegerUI defines the Jaeger UI configuration.
    enabled: false  
    route:                               # Route defines the OpenShift route configuration for the Jaeger UI.
      enabled: true                     # Enabled defines if a Route object should be created for Jaeger UI.
      annotations: {}                    # Annotations defines the annotations of the Route object.
      termination: "edge"          