apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  agent:
    ebpf:
      logLevel: info
      cacheMaxFlows: 100000
      sampling: 50
      imagePullPolicy: IfNotPresent
      excludeInterfaces:
        - lo
      kafkaBatchSize: 1048576
      cacheActiveTimeout: 5s
      features:
        - PacketDrop
        - DNSTracking
        - FlowRTT
      privileged: true
    ipfix:
      cacheActiveTimeout: 20s
      cacheMaxFlows: 400
      clusterNetworkOperator:
        namespace: openshift-network-operator
      forceSampleAll: false
      ovnKubernetes:
        containerName: ovnkube-node
        daemonSetName: ovnkube-node
        namespace: ovn-kubernetes
      sampling: 400
    type: eBPF
  consolePlugin:
    logLevel: info
    advanced:
      port: 9001
      register: true
    enable: true
    portNaming:
      enable: true
    quickFilters:
      - default: true
        filter:
          flow_layer: app
        name: Applications
      - filter:
          flow_layer: infra
        name: Infrastructure
      - default: true
        filter:
          dst_kind: Pod
          src_kind: Pod
        name: Pods network
      - filter:
          dst_kind: Service
        name: Services network
    imagePullPolicy: IfNotPresent
    autoscaler:
      maxReplicas: 3
      status: Disabled
    replicas: 1
  deploymentModel: Direct
  kafka:
    sasl:
      type: Disabled
    tls:
      enable: false
      insecureSkipVerify: false
  loki:
    advanced:
      writeMaxBackoff: 5s
      writeMaxRetries: 2
      writeMinBackoff: 1s
    writeTimeout: 10s
    microservices:
      ingesterUrl: 'http://loki-distributor:3100/'
      querierUrl: 'http://loki-query-frontend:3100/'
      tenantID: netobserv
      tls:
        enable: false
        insecureSkipVerify: false
    enable: true
    mode: LokiStack
    manual:
      authToken: Disabled
      ingesterUrl: 'http://loki:3100/'
      querierUrl: 'http://loki:3100/'
      statusTls:
        enable: false
        insecureSkipVerify: false
      tenantID: netobserv
      tls:
        enable: false
        insecureSkipVerify: false
    lokiStack:
      name: netobserv-loki
    readTimeout: 30s
    monolithic:
      tenantID: netobserv
      tls:
        enable: false
        insecureSkipVerify: false
      url: 'http://loki:3100/'
    writeBatchWait: 1s
    writeBatchSize: 102400
  namespace: netobserv
  processor:
    logLevel: info
    advanced:
      port: 2055
      conversationTerminatingTimeout: 5s
      conversationEndTimeout: 10s
      profilePort: 6060
      enableKubeProbes: true
      healthPort: 8080
      dropUnusedFields: true
      conversationHeartbeatInterval: 30s
    metrics:
      server:
        port: 9102
        tls:
          insecureSkipVerify: false
          type: Disabled
    multiClusterDeployment: false
    kafkaConsumerQueueCapacity: 1000
    imagePullPolicy: IfNotPresent
    kafkaConsumerAutoscaler:
      maxReplicas: 3
      status: Disabled
    logTypes: All
    kafkaConsumerReplicas: 3
    kafkaConsumerBatchSize: 10485760
