apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: power-monitoring-operator
  namespace: openshift-operators
spec:
  channel: tech-preview
  installPlanApproval: Automatic
  name: power-monitoring-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
