      
applications: 

  nfd-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-nfd
    source:
      path: components/nfd-operator

  nvidia-gpu-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: nvidia-gpu-operator
    source:
      path: components/nvidia-gpu-operator    

  openshift-ai:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: redhat-ods-operator
    source:
      path: components/openshift-ai

  openshift-serverless:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-serverless
    source:
      path: components/openshift-serverless 

  openshift-pipelines:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-operators
    source:
      path: components/openshift-pipelines       
                          