apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: netobserv-loki 
spec:
  size: 1x.small 
  storage:
    schemas:
      - effectiveDate: '2023-10-15'
        version: v13
    secret:
      name: logging-loki-s3 
      type: s3 
      credentialMode: static
  storageClassName: gp3-csi
  tenants:
    mode: openshift-network
  limits:
    global: 
      retention: 
        days: 2
      ingestion:
        ingestionBurstSize: 40
        ingestionRate: 20
        maxGlobalStreamsPerTenant: 25000
      queries:
        maxChunksPerQuery: 2000000
        maxEntriesLimitPerQuery: 10000
        maxQuerySeries: 3000         
  hashRing:
    type: memberlist
    memberlist:
      instanceAddrType: podIP           