apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reflector-operator

resources:
  - ./rbac.yaml  


helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    releaseName: reflector-operator
    namespace: reflector-operator
    valuesFile: values.yaml    