
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-config

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

secretGenerator:
- name: htpass-secret
  files:
  - htpasswd

resources:
  - ./oauth.yaml
  - ./admin-role-binding.yaml
  - ./olm-patch.yaml
  - ./console-patch.yaml
  - ./admin-group.yaml

generatorOptions:
 disableNameSuffixHash: true  