apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
 name: showcase.serverless.apps.${CLUSTER_BASE_DOMAIN}
spec:
 ref:
   name: showcase
   kind: Service
   apiVersion: serving.knative.dev/v1