apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: showcase
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    serving.knative.openshift.io/disableRoute: "true"
  labels:
    serverless-serving-ingress: "true"     
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true" 
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: quay.io/openshift-knative/showcase
          name: user-container	
          readinessProbe:	
            successThreshold: 1	
            tcpSocket:	
              port: 0	
          resources: {}         
          env:
            - name: GREET 
              value: Ciao