apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ${infrastructure_id} 
  name: ${infrastructure_id}-worker-gpu 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ${infrastructure_id} 
      machine.openshift.io/cluster-api-machineset: ${infrastructure_id}-worker-gpu 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${infrastructure_id} 
        machine.openshift.io/cluster-api-machine-role: worker 
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: ${infrastructure_id}-worker-gpu 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "" 
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9 
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ${infrastructure_id}-worker-profile 
          instanceType: g4dn.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2c 
            region: us-east-2 
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - ${infrastructure_id}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - ${infrastructure_id}-private-us-east-2c 
          tags:
            - name: kubernetes.io/cluster/${infrastructure_id} 
              value: owned 
          userDataSecret:
            name: worker-user-data